config/routes.rb
QiushiHuang::Application.routes.draw do
  get "qs/index"

  get "qs/story"

  get "qs/about"

  root :to=> 'qs#index'

  match '/story', :to=> 'qs#story'
  match '/about', :to=> 'qs#about'
  match '/time', :to=> 'qs#time'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/qs_controller.rb
class QsController < ApplicationController
  def index
  	@title = "Home"
  end

  def story
  	@title = "Story"
  end

  def about
  	@title = "About"
  end

  def time
  	@title = "Time"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title = "Qiushi_Huang"
		if @title.nil?
			base_title
		else
			"#{base_title}|#{@title}"
		end
	end
end

app/helpers/qs_helper.rb
module QsHelper
end

app/views/layouts/_footer.html.erb
<footer>
&copy; <%= Time.now.year %> Qiushi Huang
</footer>

app/views/layouts/_header.html.erb
<header>
<h1>Qiushi Huang's Rails Pages</h1>
<h2>After a lot of work, finally publish here</h2>
</header>

app/views/layouts/_navigation.html.erb
<style type="text/css">
.divlist{ float:left;width:600px;}
.divlist ul{ list-style-type:none;width:600px;}
.divlist li{ width:150px; float:left; }
</style>
<div class="divlist">
<nav> 
	<ul>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Story", story_path %></li> 
		<li><%= link_to "About", about_path %></li> 
		<li><%= link_to "Time", time_path %></li> 
	</ul> 
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=title%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header'%>
<%= render 'layouts/navigation'%>
</br>
<font color = '#c879ff'>
<%= yield %>
</font>
<%= render 'layouts/footer'%>
</body>
</html>

app/views/qs/about.html.erb
<h1>For My Dear Jing Yuan</h1>
<p>Written by Qiushi Huang</p>

app/views/qs/index.html.erb
<h3>Hello Jing Yuan</h3>
<h1>Find me at home -- Qiushi Huang</h1>

app/views/qs/story.html.erb
<h1>Qiushi Huang's story</h1>
<p>Em... Still haven't got a good idea</p>

app/views/qs/time.html.erb
<h1>Current time is: <%= Time.now%></h1>